### ISSUE TITLE
function.odbc-autocommitに誤訳がある

### ISSUE THREAD

**Issue by arata35** [php/doc-ja#133]
https://www.php.net/manual/ja/function.odbc-autocommit.php

> enable が true の場合は自動コミットが可能であり、 false の場合は自動コミットが使用不可となっています。

「enable が true の場合は自動コミットが**可能になり**、 false の場合は自動コミットが**使用不可になります**。」が正しいと思われます。

英語版は次のように受動文の現在形を使っていますが、これは「現時点で可能な状態にある」という状態の解釈と、「（可能ではない状態から）可能な状態に変わる」という状態変化の解釈が可能です。odbc-autocommit が自動コミットの挙動を切り替える関数であることを考えると、後者の解釈を採るほうが正しそうです。

> If enable is true, auto-commit is enabled, if it is false auto-commit is disabled.

**Comment by KentarouTakeda** [comment]
ありがとうございます！

仰る通りだと思います。頂いた文章ママで修正させて頂きました。

**Comment by arata35** [comment]
修正ありがとうございました！
