### ISSUE TITLE
array_slice() の length 引数が負の場合の訳が不正確

### ISSUE THREAD

**Issue by sigsignv** [php/doc-ja#176]
https://www.php.net/function.array_slice

> length が指定され、負の場合、配列の末尾から連続する複数の要素が返されます。

実際は「配列の末尾から指定した数だけ要素を取り除いた配列」が返されます。

```php
array_slice(['a', 'b', 'c', 'd', 'e'], 0, -1); // ['a', 'b', 'c', 'd']
array_slice(['a', 'b', 'c', 'd', 'e'], 2, -1); // ['c', 'd']
```

**Comment by KentarouTakeda** [comment]
ありがとうございます！

誤訳であることを確認し、頂いた文面ほぼそのままで修正させて頂きました。
（すぐ上の「正の場合」と表現を統一するため「指定した数」は「その数」としました）
