### ISSUE TITLE
著作権ページの修正

### ISSUE THREAD

**Issue by HiroKws** [php/doc-ja#212]
該当ページ： https://www.php.net/manual/ja/copyright.php

英語版のissue[/php/doc-en/issues/4130]とそれを修正するプルリク[/php/doc-en/pull/4305]により、Creative Commons Attribution 3.0に反する部分、日本語訳では以下の段落が削除されました。

「修正の有無に関わらず本文書の全体または一部を再配布または再出版したい場合や、 質問がある場合には、 [» doc-license@lists.php.net](mailto:doc-license@lists.php.net) 宛で著作権者まで連絡をしてください。 このアドレスは、一般にアーカイブが公開されているメーリングリストへマップされていることに 注意して下さい。」

また、「(訳注)本日本語訳の記述内容により生じたいかなる損害についても 著作権所有者および翻訳者は責任を負いません。」の記述は、ライセンスに含まれている内容と重複しているため、追記する必要はないと思われます。

ただし、4.1(d)により、「このドキュメントは、オリジナル（英語）の日本語訳です。」と新たに追記する必要があるかと思います。

参考：帰属表示の要件部分日本語訳（Claudeによる翻訳）

> 4. 帰属表示の要件
> 
> 4.1 作品または二次的著作物を頒布または公に実演する際、あなたは作品のすべての著作権表示を intact（そのまま）に保ち、あなたが利用する媒体または手段に合理的に、以下を提供しなければなりません：
> 
> (a) 提供されている場合、原著者の名前（該当する場合は筆名）、および/または原著者および/またはライセンサーが帰属を別の団体（例：後援機関、出版団体、ジャーナル）に指定している場合、その帰属が媒体に合理的な方法であることを保証しなければなりません；
> 
> (b) 提供されている場合、作品のタイトル；
> 
> (c) 合理的に実行可能な範囲で、ライセンサーが作品に関連付けるよう指定する統一資源識別子（URI）。ただし、そのURIが著作権表示またはライセンス情報を参照しない場合を除く；
> 
> (d) セクション3(b)に従い、二次的著作物の場合、作品の利用を特定するクレジット（例：「原著者による作品のフランス語訳」、または「原著者の作品に基づくシナリオ」）。
> 
> 4.2 二次的著作物の場合、原著者への帰属を、原著者が指定する合理的な方法で保持しなければなりません。
> 
> 4.3 合理的に実行可能な範囲で、ライセンサーから要求された場合、上記のセクション4.1または4.2で要求される帰属情報を削除しなければなりません。

**Comment by mumumu** [comment]
https://github.com/php/doc-ja/commit/cecdf1422046c5cc6d192918683b4ff2095b2b1e で対応しました。

> 「(訳注)本日本語訳の記述内容により生じたいかなる損害についても 著作権所有者および翻訳者は責任を負いません。」の記述は、ライセンスに含まれている内容と重複しているため、追記する必要はないと思われます。

たとえ重複していても、重ねて明示する分には問題ないと思います。
無保証であることは、ボランティアで作業するに当たり非常に重要です。
