### ISSUE TITLE
language.operators.precedence.phpの日本語訳に誤訳がある可能性

### ISSUE THREAD

**Issue by saitoyoshi** [php/doc-ja#37]
お世話になっております。issueに登録すること自体が初めてなので、なにか不手際があったら申し訳ありません。

元ページ：
https://www.php.net/manual/en/language.operators.precedence.php
該当ページ：https://www.php.net/manual/ja/language.operators.precedence.php

演算子の優先順位の表の7行目あたりで、
演算子（+ - .）の追加情報のところに「(単項の + と -),」
とありますが、元ページだと、ここが、
(binary + and -)に対応しているので、2項演算子的な意味が正しい情報ではないでしょうか？

+,-が単項の演算子として用いられる場合と、2項演算子的に用いられる場合に優先順位が異なるということだと思います。

よろしくお願いいたします。

**Comment by mumumu** [comment]
> 2項演算子的な意味が正しい情報ではないでしょうか？

正しいと思います。

御指摘の箇所は、以下の部分だと思いますが、これは 単項 (unary) 演算子に対応する 2項演算子の意味だと考えられます。誤訳なので、直しておきますね。

![Screenshot_20220326_135426](https://user-images.githubusercontent.com/26536/160225261-579e463b-ba88-428a-ac32-c72239e8772b.png)

**Comment by mumumu** [comment]
https://github.com/php/doc-ja/commit/721dc313971a0af08e6630921fc4d27f2672235e で対応しました。御報告ありがとうございました。

また何かございましたら、お気軽にお願いします :pray:
