### ISSUE TITLE
DOMDocumentFragment::appendXML generates a warning appending a data including "&".

### ISSUE THREAD

**Issue by henhenphp** [php/doc-ja#50]
From manual page: https://php.net/domdocumentfragment.appendxml

---
DOMDocumentFragment::appendXML generates a warning in my environment (PHP 8.1.6 with Windows 10) 
when appending an "a" tag data including multiple queries (including "&") as a link destination.

Try below.

$doc = new DOMDocument();
$doc->loadHTML('<!DOCTYPE html><html><head></head><body>links</body></html>', LIBXML_NOERROR);
$f = $doc->createDocumentFragment();
$data0 = '<a href="https://www.foo.net/manual/en/index.php">Foo Manual</a>';
$data1 = '<a href="https://www.foo.net/manual/en/index.php?lang=en">Foo Manual</a>';
$data2 = '<a href="https://www.foo.net/manual/en/index.php?lang=en&page=book.dom.php">Foo Manual</a>';
$f->appendXML($data0); // no error
$f->appendXML($data1); // no error
$f->appendXML($data2); // warning

echo $doc->saveHTML();

**Comment by mumumu** [comment]
> when appending an "a" tag data including multiple queries (including "&") as a link destination.
> Try below.

Your sample does not append `"a"` tag, and cannot reproduce warning.
