### ISSUE TITLE
極めてどうでも良いが

### ISSUE THREAD

**Issue by irukanohito** [php/doc-ja#68]
From manual page: https://php.net/function.imagecreatefromstring

---

Not "認識できない書式のデータを受け取った場合に、 imagecreatefromstring() は E_WARNING レベルのエラーを発酵します。 " but "認識できない書式のデータを受け取った場合に、 imagecreatefromstring() は E_WARNING レベルのエラーを発行します。" in Japanese site.

**Comment by mumumu** [comment]
報告ありがとうございます。https://github.com/php/doc-ja/commit/052d47f51a9ab70f1cc94eec8819869f336c2b5d で対応させて頂きました :pray:
